# Generated by Django 3.0.7 on 2020-08-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='label',
        ),
        migrations.AddField(
            model_name='note',
            name='labels',
            field=models.CharField(choices=[('P', 'primary'), ('SE', 'secondary'), ('S', 'success'), ('D', 'danger'), ('W', 'warning'), ('I', 'info'), ('L', 'light'), ('D', 'dark')], default='primary', max_length=2),
            preserve_default=False,
        ),
    ]
